# Generated by Django 4.2.6 on 2023-10-16 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_follows'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Follows',
            new_name='Follow',
        ),
    ]
